### ISSUE TITLE
`pip install` doesn't include all requirements

### ISSUE THREAD

**Issue by rhigman** [thoth-pub/thoth-client#27]
The behaviour when installing with pip is different from the behaviour when installing from the repo (following both sets of install instructions in the README). `pip install` omits the required package `fire`, which means that `thothlibrary.cli` fails to run with a ModuleNotFound error. When installed from the repo, `thothlibrary.cli` runs fine.

`fire` is correctly listed in `requirements.txt` and `publish-to-pypi.yaml` installs those requirements as part of the build process.

A workaround is to `pip install fire` separately after `pip install`ing thothlibrary.

**Comment by MartinPaulEve** [comment]
Thanks for this.

@ja573: I think the solution is to add "fire" (and any other requirements) to install_requires=["graphqlclient", "requests", "munch"] in setup.py?
